apiVersion: v1
kind: ConfigMap
metadata:
  name: netlab-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  DB_CONNECTION: "pgsql"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_DATABASE: "netlab"
  DB_USERNAME: "netlab"
  CML_API_BASE_URL: "https://54.38.146.213"
  CML_USERNAME: "cheick"
---
apiVersion: v1
kind: Secret
metadata:
  name: netlab-secrets
type: Opaque
stringData:
  APP_KEY: "base64:UseYourAppKeyHere..." # You should generate one
  DB_PASSWORD: "password"
  CML_PASSWORD: "cheick2025"
